### ISSUE TITLE
docker-compose up fails

### ISSUE THREAD

**Issue by kostajh** [fubhy/drupal-decoupled-app#380]
I think there might be a service definition missing from your `docker-compose.yml`, when I run `docker-compose up -d` I get:

```
15:19 $ docker-compose up -d
ERROR: Service "drupal" mounts volumes from "amazeeio-ssh-agent", which is not the name of a service or container.
```

**Comment by fubhy** [comment]
@Schnitzel This happens when one doesn't have amazee.io running, right?

**Comment by fubhy** [comment]
@kostajh As stated in the README in the pre-requisites section, can you try to install amazee.io first? Otherwise you can also just run the backend however you normally run Drupal on your local machine and adapt the API host env variables in your frontend accordingly and configure CORS yourself. (With the .amazee.io configuration in the .amazee.io folder in the root, we normally do that for you automatically).

**Comment by kostajh** [comment]
Ah, sorry I totally missed the link to https://docs.amazee.io . It might be worth adding another callout to this at the start of the [Usage section](https://github.com/fubhy/drupal-decoupled-app#usage)

**Comment by fubhy** [comment]
Yes, documentation is severely lacking currently, agreed. That's my weak spot ;)

**Comment by kclarkson** [comment]
@fubhy it would nice to add the installation terminal steps to  https://docs.amazee.io  on the README file. :)

**Comment by fubhy** [comment]
@kclarkson Sorry, I don't understand what you mean. There is already a link to docs.amazee.io in the README file (see the Prerequisites section at the top).

**Comment by Schnitzel** [comment]
I think we can do better, sent a pull request: https://github.com/fubhy/drupal-decoupled-app/pull/384

**Comment by milkovsky** [comment]
Also faced this issue. You need to [install pygmy](https://docs.amazee.io/local_docker_development/pygmy.html).

**Important:** If you are using Ubuntu - make sure the ports 53 and 80 are not used.
To free up the port 53 do what is written at the docs page:

> If you are on Ubuntu, disable the DNS that is started by default, see: http://askubuntu.com/a/233223

To free up other ports check the `sudo netstat -tulpn| grep 80`. E.g. the port 80 may be used by apache2.
