### ISSUE TITLE
Yarn cannot find persistgraphql

### ISSUE THREAD

**Issue by drupov** [fubhy/drupal-decoupled-app#382]
I get an unexpected error on `yarn install` with trace:

`Error: https://registry.yarnpkg.com/@amazee/persistgraphql/-/persistgraphql-0.3.2.tgz: invalid tar file`

**Comment by fubhy** [comment]
Interesting. That was reported before too. I wonder how that's possible considering that the package is definitely public. What version of yarn are you on?

**Comment by fubhy** [comment]
Can you try again now?

**Comment by drupov** [comment]
Works now, thanks!

Just for information, I get some warnings though:
```
yarn install v0.16.0
[1/4] Resolving packages...
[2/4] Fetching packages...
warning fsevents@1.0.14: The platform "linux" is incompatible with this module.
info "fsevents@1.0.14" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning Unmet peer dependency "graphql@^0.9.x".
[4/4] Building fresh packages...
success Saved lockfile.
Done in 17.00s.
```
