### ISSUE TITLE
docker-compose up -d: Command Not Found

### ISSUE THREAD

**Issue by kclarkson** [fubhy/drupal-decoupled-app#383]
When trying to run docker-compose up -d.

I get command not found.  I have tried docker and it gives me the help of the different command. I double checked that the yml file was correctly named but I am still getting the error.

**Comment by fubhy** [comment]
You need to also install docker-compose in addition to docker. Optimally you should run the .amazee.io dev environment for the best experience. Please refer to http://docs.amazee.io for installation instructions. If you would rather not want to install that, you can of course also just use whatever hosting / local development setup you usually use for Drupal and just change the configuration in the .env file in the /frontend directory to point to the URL of that environment. Note that you will then also have to configure CORS yourself (with amazee.io you get that out of the box).
