### ISSUE TITLE
Unable to include static files in frontend build

### ISSUE THREAD

**Issue by danielkorte** [fubhy/drupal-decoupled-app#386]
Thanks for the demo! I really appreciate it.

I'm wondering if there is a way to include static files in the build folder similar to how the create-react-app copies the public folder content to the build directory:
https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#using-the-public-folder

Also, is there any reason this approach/file structure should not be used in production?

**Comment by danielkorte** [comment]
I looked through @amazee/react-scripts, but it doesn‘t appear that copying static files automatically is possible. For now, I simply modified my package.json build script to be: `react-scripts build && cp public/* build/public` which is working for me.

**Comment by fubhy** [comment]
We do that with loaders. Just import the files you want to copy in your javascript. Currently we do not support custom webpack config for additional loaders but fonts, images (svg, png, jpg, gif), css, etc. work. This is just a demo app for now but I might make it more configurable / extendable in the future.

**Comment by danielkorte** [comment]
Got it. Thanks!
